### ISSUE TITLE
Extract license metadata from Rmd header

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#96]
To streamline the upload process of **workspaces** it would be good to extract license metadata from R Markdown headers. The headers are already parsed via https://github.com/o2r-project/o2r-meta/blob/5c12559803106db3ded76de661696a9414728f7d/parsers/parse_yaml.py (@7048730 correct?) so the yaml parser must simply be extended to also extract 

```yaml
---
title: "Capacity of container ships in seaborne trade from 1980 to 2016 (in million dwt)*"
licenses:
    code: Apache-2.0
    data: ODbL-1.0
    text: CC0-1.0
    ui_bindings: CC0-1.0
    metadata: CC0-1.0
---
```

Should update the testfile at https://raw.githubusercontent.com/o2r-project/o2r-meta/master/extract/tests/minimal/main.Rmd

Related to #90 

_Motivation:_ For the corpus, we want to be able to upload and publish papers without any actions from a user.
